baseurl = "https://cppoxford.github.io/"
languageCode = "en-gb"
title = "C++ Oxford"
paginate = 10
pygmentsUseClasses = true
pygmentsCodefences = true
googleAnalytics = "UA-140848718-2"
enableGitInfo = true
disableKinds = ["section", "taxonomyTerm", "RSS"]

[permalinks]
    blog = "/:slug/"
    page = "/:slug/"

[[menu.main]]
    name = "People"
    url = "/people/"
    weight = -150

[[menu.main]]
    name = "Events"
    url = "/events/"
    weight = -120

[params]
    description = ""

    [params.logo]
    url = "people/placeholder.svg"
    alt = "placeholder logo"
