name: deploy website

on:
  push:
    branches:
      - master

jobs:

  build-and-test:
    name: build and deploy website
    runs-on: ubuntu-latest

    steps:
      - name: fetch this repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: install hugo
        run: |
          sudo snap install hugo

      - name: build website
        run: |
          hugo
        env:
          GIT_CONFIG_NOSYSTEM: true

      - name: fetch live site repo
        uses: actions/checkout@v2
        with:
          repository: CppOxford/cppoxford.github.io
          token: ${{ secrets.DEPLOY_ACCESS_TOKEN }}
          path: live-site
          fetch-depth: 0
      
      - name: test
        run: |
          ls -l

      # - name: deploy website
      #   run: |
      #     git clone https://github.com/CppOxford/cppoxford.github.io.git
      #     rm cppoxford.github.io/404.html
      #     rm cppoxford.github.io/index.html
      #     rm cppoxford.github.io/sitemap.xml
      #     rm -rf cppoxford.github.io/css
      #     rm -rf cppoxford.github.io/events
      #     rm -rf cppoxford.github.io/images
      #     rm -rf cppoxford.github.io/people
      #     rm -rf cppoxford.github.io/site-notice
      #     cp -r public/* cppoxford.github.io
      #     cd cppoxford.github.io
      #     git add --all
      #     git -c user.name='github-action' -c user.email='github-action' commit -a -m "deploy website"
      #   working-directory: live-site
