name: deploy website

on:
  push:
    branches:
      - master

jobs:

  build-and-test:
    name: build and deploy website
    runs-on: ubuntu-latest

    steps:
      - name: fetch this repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: install hugo
        run: |
          sudo snap install hugo

      - name: build website
        run: |
          hugo
        env:
          GIT_CONFIG_NOSYSTEM: true

      - name: fetch live site repo
        uses: actions/checkout@v2
        with:
          repository: CppOxford/cppoxford.github.io
          token: ${{ secrets.DEPLOY_ACCESS_TOKEN }}
          path: cppoxford.github.io
          fetch-depth: 0
      
      - name: clean live site repo
        working-directory: cppoxford.github.io
        # this should not remove hidden files (.git)
        run: |
          rm -rf *
      
      - name: copy to live site repo
        run: |
          cp -r public/* cppoxford.github.io
      
      - name: deploy live site
        working-directory: cppoxford.github.io
        run: |
          git add --all
          git -c user.name='github-action' -c user.email='github-action' commit -a -m "deploy website"
          git push
